### ISSUE TITLE
Using {} as a hash

### ISSUE THREAD

**Issue by arb** [cjihrig/insync#16]
I'm sure async is vulnerable to this as well, but in this example

```javascript
Insync.auto({
    'hasOwnProperty': function (callback) {
        callback(null, 'hasOwnProperty');
    },
    'bind' : function (callback) {
        setTimeout(function() {

            callback(null, 'bind');
        }, 100);
    }
}, function (err, results) {

    expect(err).to.not.exist();
    expect(results).to.deep.equal({
        hasOwnProperty: 'hasOwnProperty',
        bind: 'bind'
    });

    done();
});
```

will cause an obvious hard error. I suggest we create any collector objects with `var results = Object.create(null)`. While there will probably be a _slight_ performance hit for it, it will require the least amount of code rework.

This could be another place for a sweet macro by the way.

**Comment by cjihrig** [comment]
I've changed my mind. We recently dealt with this exact thing on io.js, and only treated it as a bug fix.

**Comment by arb** [comment]
I'll take this then!

**Comment by cjihrig** [comment]
Going to close this for now.
